repos:
# Official repo for default hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: check-xml
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer
# black repo for python formatting
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
    - id: black
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
    - id: codespell
- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 1.3.1
  hooks:
    - id: tox-ini-fmt
